### ISSUE TITLE
help for go's 'append()'

### ISSUE THREAD

**Issue by JieshuaiCui** [AppliedGo/concurrencyslower#3]
```   
package main

import (
	"fmt"
)

func main() {
	x := make([]int, 1, 10)

	var a []int
	fmt.Println("                 a                                                         x ")
	for i := 0; i < 12; i++ {

		a = append(x, i)
		fmt.Printf("%p---%p---%v----%v---%v   ===   %p---%p---%v----%v---%v\n", a, &(a[0]), len(a), cap(a), a, x, &(x[0]), len(x), cap(x), x)
	}

	fmt.Println("--------------------------------------------------")
	fmt.Printf("%p---%p---%v----%v---%v   ===   %p---%p---%v----%v---%v\n", a, &(a[0]), len(a), cap(a), a, x, &(x[0]), len(x), cap(x), x)
	fmt.Println("a:", a)
	fmt.Println("x:", x)
}


```
![image](https://user-images.githubusercontent.com/24765224/65900784-58e81280-e3e9-11e9-9727-22f8e401782b.png)

I don't know the theory;please give me a answer!!thank you

**Comment by christophberger** [comment]
Hi , 
thanks for reaching out to me. May I just ask to use the Issue system only for reporting issues with the code in this repository. 

For general questions about Go, there are better places to ask, such as:
* The comments section in the respective blog article
* The Go subreddit at https://reddit.com/r/golang
* The Go forum at https://forum.golangbridge.org/

The advantage is that more people see your question and can share their thoughts.

I have moved your question into this gist and answered it there:
https://gist.github.com/christophberger/1d6e1a8192a271e14ad7fb9df01528f2

Let's continue the discussion over there, thanks!
